version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: monthly
    labels:
      - "maintenance"
      - "dependencies"
    groups:
      dependencies:
          patterns:
            - "*"
    ignore:
      - dependency-name: "dulwich:*"
        versions: [ ">0.21.3" ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    labels:
      - "maintenance"
    groups:
       actions:
          patterns:
            - "*"
