repos:

- repo: https://github.com/ansys/pre-commit-hooks
  rev: v0.4.3
  hooks:
    - id: add-license-headers
      args:
      - --start_year=2023

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.4
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format

- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    additional_dependencies:
      - tomli
    exclude: >
        (?x)^(
            .*\.etp|
            .*\.vsw|
            .*\.scade|
            .*\.xscade
        )$

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: check-yaml
  - id: trailing-whitespace
